#!/usr/bin/env python3
import logging
import os
import shutil
import sys
import imp
import traceback
import time
import irc
import bot

logger = logging.getLogger(__name__)

CONF_PATH = '~/.scythebot/config.py'
CONF_PATH = os.path.expanduser(os.path.expandvars(CONF_PATH))

if __name__ == '__main__':
    script_dirname = os.path.dirname(os.path.realpath(__file__))
    conf_dirname = os.path.dirname(CONF_PATH)
    if not os.path.isdir(conf_dirname):
        src = os.path.join(script_dirname, 'config')
        shutil.copytree(src, conf_dirname)
        print('New configuration was created in {0}'.format(conf_dirname))
        sys.exit()
    if not os.path.isfile(CONF_PATH):
        src = os.path.join(script_dirname, 'config/config.py')
        shutil.copyfile(src, CONF_PATH)
        print('New configuration file was created in {0}'.format(CONF_PATH))
        sys.exit()

    config = imp.load_source('config', CONF_PATH)

    logging.basicConfig(filename=config.log_file, \
            level=getattr(logging, config.log_level.upper()), \
            format=config.log_format, datefmt=config.log_datefmt)

    logger.debug('Config file: %s', CONF_PATH)
    logger.debug('Modules paths: %s', config.modules_paths)

    ircbot = bot.Bot(config)
    while 1:
        try:
            ircbot.connect()
            ircbot.main_loop()
        except KeyboardInterrupt as exc:
            ircbot.quit()
            sys.exit()
        except irc.LostConnectionException as exc:
            logger.error('Lost connection with the irc network')
            ircbot.close()
            time.sleep(config.cooldown or 5)
            continue
        except irc.ConnectionFailureException as exc:
            logger.error('Cannot connect to the irc network')
            sys.exit()
        except BaseException as exc:
            traceback.print_exc()
            ircbot.close()
            sys.exit()
