#!/usr/bin/env python3
import logging
import imp
import traceback
import bot

logger = logging.getLogger(__name__)

CONF_PATH = 'config.py'

if __name__ == '__main__':
    config = imp.load_source('config', CONF_PATH)

    logging.basicConfig(
        filename=config.log_file,
        level=getattr(logging, config.log_level.upper()),
        format=config.log_format, datefmt=config.log_datefmt
    )

    logger.debug('Config file: %s', CONF_PATH)
    logger.debug('Modules paths: %s', config.modules_paths)

    ircbot = bot.Bot(config)
    try:
        ircbot.main()
    except KeyboardInterrupt:
        pass
    except Exception as exc:
        traceback.print_exc()
    finally:
        ircbot.close()
